[package]
name = "armerge"
version = "1.2.0"
authors = ["tux3 <barrdetwix@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/tux3/armerge/"
categories = ["command-line-utilities", "development-tools::build-utils"]
description = "Tool to merge and control visibility of static libraries"

[dependencies]
objpoke = { version = "0.1", optional = true }
structopt = "0.3"
ar = "0.8"
tempdir = "0.3.7"
rand = "0.7.3"
object = "0.23"
regex = "1.3.9"
rayon = "1.4.0"
which = "4.0.2"
